### PR TITLE
Fix boot problem with GCC 12.1

### PR DESCRIPTION
**Pull request by WXbet**
Standard CFLAGS is -Os, which lets dm525 not boot. With CFLAGS -O2 the boot process hangs too.

### CODE REVIEW

**Comment by persianpros** [comment]
Can you confirm if we add

export KCFLAGS:mips += "-O1"

to the end of https://github.com/OpenVisionE2/openvision-development-platform/blob/develop/meta-openvision/classes/samba_change_dialect.bbclass we will get the same result?

**Comment by WXbet** [comment]
Are you sure thios is the right place? samba_change_dialect.bbclass is inherited in so many recipes... And maybe we need this change only for special stb's/old linux versions.

**Comment by WXbet** [comment]
Adding

`export KCFLAGS:mips += "-O1"`

to the end of https://github.com/OpenVisionE2/openvision-development-platform/blob/develop/meta-openvision/classes/samba_change_dialect.bbclass we get this error:

`export: `KCFLAGS:mips= -O1': not a valid identifier`

See: https://buildbot.openvision.dedyn.io/logfiles/OpenVisionTest/build/1104/

**Comment by persianpros** [comment]
What if you add:

if [ "${TARGET_ARCH}" = "mips" ]; then
		export KCFLAGS = "-O1"
fi

?

**Comment by WXbet** [comment]
ERROR: ParseError at /home/abcde/worker-test/OpenVisionTest/build/meta-openvision/classes/samba_change_dialect.bbclass:41: unparsed line: 'if [ "${TARGET_ARCH}" = "mips" -o "${TARGET_ARCH}" = "mips32el" ]; then'
ERROR: Parsing halted due to errors, see error messages above

**Comment by WXbet** [comment]
This seems to work:

```
do_openvision_add_kcflags(){
	if [ "${TARGET_ARCH}" = "mips" -o "${TARGET_ARCH}" = "mips32el" ]; then
		export KCFLAGS += "-O1" || true
	fi
}
addtask openvision_add_kcflags before do_configure after do_patch
```

**Comment by persianpros** [comment]
Ok then that's the better solution as that will apply to all mipsel kernels ;)

I did a mistake though, change mips32el to mipsel as mips32el is TUNE not ARCH

**Comment by WXbet** [comment]
> Ok then that's the better solution as that will apply to all mipsel kernels ;)
Do we know if all the mipsel kernels have that boot problem with gcc-12?

> I did a mistake though, change mips32el to mipsel as mips32el is TUNE not ARCH
I'll update the PR.

**Comment by WXbet** [comment]
New PR: https://github.com/OpenVisionE2/openvision-development-platform/pull/236

**Pull request closed without merging**
