### PR TITLE
Fix bitbake git branch warning

### PR DESCRIPTION
**Pull request by WXbet**

### CODE REVIEW

**Comment by persianpros** [comment]
This is wrong, dreambox has different branches for different models.

I have to check this myself.

**Comment by persianpros** [comment]
I'm sure not all

recipes-bsp/extra/libpagecache_0.0.4.bb:inherit autotools opendreambox-git pkgconfig
recipes-bsp/extra/libdlsym_0.0.1.bb:inherit autotools opendreambox-git lib_package pkgconfig
recipes-bsp/extra/mkbootblob_1.0.bb:inherit autotools opendreambox-git
recipes-bsp/recovery/recovery-ui_1.1.bb:inherit opendreambox-git pkgconfig update-rc.d
recipes-bsp/recovery/recovery_1.1.bb:inherit opendreambox-git
recipes-bsp/recovery/recovery-web_1.0.3.bb:inherit opendreambox-git

are using master branch.

**Comment by WXbet** [comment]
recipes-bsp/extra/libpagecache_0.0.4.bb:inherit autotools opendreambox-git pkgconfig -> only master branch exists
recipes-bsp/extra/libdlsym_0.0.1.bb:inherit autotools opendreambox-git lib_package pkgconfig -> only master branch exists
recipes-bsp/extra/mkbootblob_1.0.bb:inherit autotools opendreambox-git -> only master branch exists
recipes-bsp/recovery/recovery-ui_1.1.bb:inherit opendreambox-git pkgconfig update-rc.d -> branches master, dm7080 exists
recipes-bsp/recovery/recovery_1.1.bb:inherit opendreambox-git -> branches master, dm820, dm7080, dm520, dm900 exists
recipes-bsp/recovery/recovery-web_1.0.3.bb:inherit opendreambox-git -> branches master, dm7080, dm520, dm900, dreamone exists

**Comment by persianpros** [comment]
https://github.com/OpenVisionE2/meta-dreambox/commit/f4144d320150fc247b5e489c320d213a7685eeae should fix it

**Comment by WXbet** [comment]
Looks good. I test it after submodules using submodule.sh update for openvision-development-platform and openvision-oe

**Pull request closed without merging**
